version: "3.7"
services:
  apache:
    image: phpapache
    container_name: myapache
    depends_on:
    - mysql
    build:
      context: .
      dockerfile: apache-php.docker
    ports:
    - "88:80"
    restart: unless-stopped
    links:
    - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 3s
      retries: 2
      start_period: 15s

  mysql:
    image: mysql:8
    container_name: lamp_mysql
    logging:
      driver: none
    environment:
    - "MYSQL_ROOT_PASSWORD=1234"
# nem kell kinyitni a portot, mert egy halozaton vannak
volumes:
  db:
