version: "3.7"
services:
  influx:
    image: influxdb:1.7
    container_name: influx
    ports:
    - "8086:8086"
    - "8083:8083"

  telegraf:
    image: telegraf:1.12
    container_name: telegraf
    ports:
    - "8094:8094"
    depends_on:
    - influx
#    configs:
#    - source: telegraf-conf
#      target: /etc/telegraf/telegraf.conf
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:Z
  
  chronograf:
    image: chronograf
#    build:
#      context: .
#      dockerfile: Dockerfile.chrono
    container_name: chronograf
    ports:
    - "8888:8888"
    depends_on:
    - influx
    environment:
      - INFLUXDB_URL=http://influx:8086
#configs:
#  telegraf-conf:
#    file: ./telegraf.conf

